In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
path = 'https://frenzy86.s3.eu-west-2.amazonaws.com/python/data/realcase/dataset_costi.xlsx'
df=pd.read_excel(path, keep_default_na=False)
df = df.drop(columns=['index'])
df

,Ragione sociale,costi anno 2020,var1,var2,var3,var4,var5,var6,var7,var8,...,Numero CCIAA,Codice fiscale,Partita IVA,var153,var154,var155,var156,var157,var158,var159
0,company101,144205134,147823139,148193655,0,0,0,51344312,61401789,71387976,...,20680,256,10696,84978,318158,318158,25290616,24108358,24535319,Produ
1,company102,140165127,147562322,163251010,0,0,0,1037776,1391301,1602930,...,20681,257,10697,1583,1583,1588,14133394,10404117,12898505,Produ
2,company103,145190000,147562000,142652000,0,0,0,737000,707000,745000,...,20682,258,10698,1801000,1761000,1171000,31861000,22494000,24687000,Produ
3,company104,112760368,147067625,140160124,0,0,0,39316,5715,8015,...,20683,259,10699,890646,0,0,1000000,0,1188439,Produ
4,company105,171980718,145273739,127413305,0,0,0,6571906,3613836,3218188,...,20684,260,10700,0,0,0,27325115,24037285,24492237,Produ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7919,company8020,81879,n.d.,n.d.,0,n.d.,n.d.,1500,n.d.,n.d.,...,28599,8175,18615,0,n.d.,n.d.,0,n.d.,n.d.,Produ
7920,company8021,80757,n.d.,n.d.,0,n.d.,n.d.,1500,n.d.,n.d.,...,28600,8176,18616,0,n.d.,n.d.,0,n.d.,n.d.,Produ
7921,company8022,74478,n.d.,n.d.,7000,n.d.,n.d.,2529,n.d.,n.d.,...,28601,8177,18617,0,n.d.,n.d.,0,n.d.,n.d.,Produ
7922,company8023,0,n.d.,n.d.,0,n.d.,n.d.,0,n.d.,n.d.,...,28602,8178,18618,5253,n.d.,n.d.,303714,n.d.,n.d.,Produ
7923,company8024,0,n.d.,169365,0,n.d.,0,195790,n.d.,211773,...,28603,8179,18619,0,n.d.,0,489502,n.d.,646356,Produ

In [28]:
stringa_da_sostituire = "n.d."
df = df.replace(stringa_da_sostituire, 0)
colonne_da_convertire = [col for col in df.columns if col != 'Ragione sociale']

C:\Users\0304f\AppData\Local\Temp\ipykernel_34300\878757421.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(stringa_da_sostituire, 0)

In [39]:
df.fillna(0)
numeric_cols = df.select_dtypes(include=['number']).columns
medians = df[numeric_cols].median()
df[numeric_cols] = df[numeric_cols].apply(lambda x: x.replace(0, medians[x.name]))
df=df.drop(columns=["var159","var144","var145","var146"])

KeyError: "['var159', 'var144', 'var145', 'var146'] not found in axis"

In [41]:
numeric_cols = df.select_dtypes(include=['number']).columns
modes = df[numeric_cols].mode().iloc[0]
df[numeric_cols] = df[numeric_cols].apply(lambda x: x.replace(0, modes[x.name]))

In [42]:
df = df.select_dtypes(exclude=['object'])

In [46]:
df=df.drop(columns=["Numero CCIAA","Codice fiscale","Partita IVA"])

In [47]:
df

,costi anno 2020,var1,var2,var3,var4,var5,var6,var7,var8,var9,...,var149,var150,var151,var152,var153,var154,var155,var156,var157,var158
0,144205134,147823139,148193655.0,0,0,0,51344312,61401789.0,71387976.0,23064675,...,3813249.0,229,214,207,84978,318158,318158,25290616.0,24108358,24535319
1,140165127,147562322,163251010.0,0,0,0,1037776,1391301.0,1602930.0,23503659,...,2204557.0,454,411,456,1583,1583,1588,14133394.0,10404117,12898505
2,145190000,147562000,142652000.0,0,0,0,737000,707000.0,745000.0,51250000,...,2408000.0,116,165,168,1801000,1761000,1171000,31861000.0,22494000,24687000
3,112760368,147067625,140160124.0,0,0,0,39316,5715.0,8015.0,5258584,...,473999.0,60,60,65,890646,0,0,1000000.0,85859,1188439
4,171980718,145273739,127413305.0,0,0,0,6571906,3613836.0,3218188.0,65670888,...,869544.0,171,141,132,0,0,0,27325115.0,24037285,24492237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7919,81879,1478972,1349412.5,0,0,0,1500,10004.5,7893.5,303505,...,10156.5,10,9,8,0,0,0,102919.5,85859,65776
7920,80757,1478972,1349412.5,0,0,0,1500,10004.5,7893.5,303505,...,10156.5,29,9,8,0,0,0,102919.5,85859,65776
7921,74478,1478972,1349412.5,7000,0,0,2529,10004.5,7893.5,303505,...,10156.5,1,9,8,0,0,0,102919.5,85859,65776
7922,1611384,1478972,1349412.5,0,0,0,13038,10004.5,7893.5,16295937,...,10156.5,9,9,8,5253,0,0,303714.0,85859,65776
7923,1611384,1478972,169365.0,0,0,0,195790,10004.5,211773.0,735210,...,24121.0,9,9,9,0,0,0,489502.0,85859,646356

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [50]:
target = 'costi anno 2020'
X = df.drop(target,axis=1).values
y = df[target].values

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.3,
                                                    random_state=667,
                                                    )

In [1]:
def overfit_eval(model, X, y):

    """
    model: il nostro modello predittivo già addestrato
    X: una tupla contenente le prorietà del train set e test set (X_train, X_test)
    y: una tupla contenente target del train set e test set (y_train, y_test)
    """

    y_pred_train = model.predict(X[0])
    y_pred_test = model.predict(X[1])

    mse_train = mean_squared_error(y[0], y_pred_train)
    mse_test = mean_squared_error(y[1], y_pred_test)

    r2_train = r2_score(y[0], y_pred_train)
    r2_test = r2_score(y[1], y_pred_test)

    print("Train set:  MSE="+str(mse_train)+" R2="+str(r2_train))
    print("Test set:  MSE="+str(mse_test)+" R2="+str(r2_test))

In [ ]:
from sklearn.linear_model import Lasso

alphas = [0.0001, 0.001, 0.01, 0.1 ,1 ,10] #alpha corrisponde a lambda

for alpha in alphas:
    print("Alpha="+str(alpha))
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_train_poly, y_train)

    overfit_eval(lasso, (X_train_poly, X_test_poly),(y_train, y_test))

Alpha=0.0001