In [139]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [140]:
url = 'house.csv'
df = pd.read_csv(url, keep_default_na=False)
df = df.drop(columns=['Unnamed: 0'])
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [141]:
df.corr()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
Price,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [142]:
X = df[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
B0=model.intercept_
B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13=model.coef_
print(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13)

-0.13347010285294628 0.035808913593231226 0.04952264522005423 3.1198351162854276 -15.417060895306818 4.057199231645385 -0.01082083518492994 -1.3859982431608784 0.24272733982225278 -0.008702234365662476 -0.9106852081102911 0.011794115892572418 -0.5471133128239585

In [143]:
y_pred=model.predict(X_test)

In [144]:
pd.DataFrame(list(zip(y_pred,y_test)),columns=['predicted','true'])

     predicted  true
0    28.648960  23.6
1    36.495014  32.4
2    15.411193  13.6
3    25.403213  22.8
4    18.855280  16.1
..         ...   ...
147  17.403672  17.1
148  13.385941  14.5
149  39.983425  50.0
150  16.682863  14.3
151  18.285618  12.6

[152 rows x 2 columns]

In [145]:
length = len(y_test) #y_pred.shape[0]
x=np.linspace(0,length,length)

In [146]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y_test, name="real", mode="lines"))
fig.add_trace(go.Scatter(x=x, y=y_pred, name="predicted", mode="lines"))
fig.update_layout(title="Error from prediction on Test Set", xaxis_title="Obeservation", yaxis_title="Value",width=900)
fig.show()

In [147]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [148]:
polyfeats = PolynomialFeatures(degree=2)
X_train_poly = polyfeats.fit_transform(X_train)
X_test_poly = polyfeats.transform(X_test)

print("Numero di esempi nel test: "+str(X_train_poly.shape[0]))
print("Numero di features: "+str(X_train_poly.shape[1]))

Numero di esempi nel test: 354
Numero di features: 105

In [149]:
ss = StandardScaler()
X_train_poly = ss.fit_transform(X_train_poly)
X_test_poly = ss.transform(X_test_poly)

In [150]:
def overfit_eval(model, X, y):

    """
    model: il nostro modello predittivo già addestrato
    X: una tupla contenente le prorietà del train set e test set (X_train, X_test)
    y: una tupla contenente target del train set e test set (y_train, y_test)
    """

    y_pred_train = model.predict(X[0])
    y_pred_test = model.predict(X[1])

    mse_train = mean_squared_error(y[0], y_pred_train)
    mse_test = mean_squared_error(y[1], y_pred_test)

    r2_train = r2_score(y[0], y_pred_train)
    r2_test = r2_score(y[1], y_pred_test)

    print("Train set:  MSE="+str(mse_train)+" R2="+str(r2_train))
    print("Test set:  MSE="+str(mse_test)+" R2="+str(r2_test))

In [151]:
ll = LinearRegression()
ll.fit(X_train_poly, y_train)

overfit_eval(ll, (X_train_poly, X_test_poly),(y_train, y_test))

Train set:  MSE=4.660318639997262 R2=0.9469794920108195
Test set:  MSE=25.257540307734452 R2=0.6610321968877308

In [152]:
from sklearn.linear_model import Ridge

alphas = [0.0001, 0.001, 0.01, 0.1 ,1 ,10] #alpha corrispone a lambda

for alpha in alphas:
    print("Alpha="+str(alpha))
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train_poly, y_train)

    overfit_eval(ridge, (X_train_poly, X_test_poly),(y_train, y_test))

Alpha=0.0001
Train set:  MSE=4.663400389591398 R2=0.9469444309041445
Test set:  MSE=24.906273733239075 R2=0.6657463558126602
Alpha=0.001
Train set:  MSE=4.682093892214437 R2=0.9467317546728103
Test set:  MSE=24.197074946655533 R2=0.6752641295835485
Alpha=0.01
Train set:  MSE=4.791911930268351 R2=0.9454823533735042
Test set:  MSE=22.987682948300748 R2=0.6914947262207969
Alpha=0.1
Train set:  MSE=5.247017382959914 R2=0.9403046125033291
Test set:  MSE=19.554794525793074 R2=0.7375656671251507
Alpha=1
Train set:  MSE=6.710895368644498 R2=0.9236500529268575
Test set:  MSE=12.611356539880749 R2=0.8307497971494925
Alpha=10
Train set:  MSE=10.375853711096983 R2=0.8819537724604795
Test set:  MSE=12.543575179949968 R2=0.8316594541623198

In [153]:
from sklearn.linear_model import Ridge

alphas = [0.0001, 0.001, 0.01, 0.1 ,1 ,10] #alpha corrispone a lambda

for alpha in alphas:
    print("Alpha="+str(alpha))
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train_poly, y_train)

    overfit_eval(ridge, (X_train_poly, X_test_poly),(y_train, y_test))

Alpha=0.0001
Train set:  MSE=4.663400389591398 R2=0.9469444309041445
Test set:  MSE=24.906273733239075 R2=0.6657463558126602
Alpha=0.001
Train set:  MSE=4.682093892214437 R2=0.9467317546728103
Test set:  MSE=24.197074946655533 R2=0.6752641295835485
Alpha=0.01
Train set:  MSE=4.791911930268351 R2=0.9454823533735042
Test set:  MSE=22.987682948300748 R2=0.6914947262207969
Alpha=0.1
Train set:  MSE=5.247017382959914 R2=0.9403046125033291
Test set:  MSE=19.554794525793074 R2=0.7375656671251507
Alpha=1
Train set:  MSE=6.710895368644498 R2=0.9236500529268575
Test set:  MSE=12.611356539880749 R2=0.8307497971494925
Alpha=10
Train set:  MSE=10.375853711096983 R2=0.8819537724604795
Test set:  MSE=12.543575179949968 R2=0.8316594541623198

In [154]:
from sklearn.linear_model import ElasticNet

alphas = [0.0001, 0.001, 0.01, 0.1 ,1 ,10]

for alpha in alphas:
    print("Lambda is: "+str(alpha))
    elastic = ElasticNet(alpha=alpha, l1_ratio=0.5)
    elastic.fit(X_train_poly, y_train)
    overfit_eval(elastic, (X_train_poly, X_test_poly),(y_train, y_test))

Lambda is: 0.0001
Train set:  MSE=5.923827722598889 R2=0.9326045321457316
Test set:  MSE=27.40048906588721 R2=0.6322728393302267
Lambda is: 0.001

Train set:  MSE=6.032547526882557 R2=0.9313676254668338
Test set:  MSE=22.391935846591647 R2=0.6994899262211309
Lambda is: 0.01
Train set:  MSE=7.608580680378898 R2=0.9134370750342962
Test set:  MSE=11.623945987361534 R2=0.8440013007274089
Lambda is: 0.1
Train set:  MSE=14.24069382598397 R2=0.8379834343746718
Test set:  MSE=15.802307593079805 R2=0.787925766972237
Lambda is: 1
Train set:  MSE=23.3311409735596 R2=0.7345612946358449
Test set:  MSE=22.877504582558625 R2=0.6929733705436834
Lambda is: 10
Train set:  MSE=72.44541538875212 R2=0.1757875325449656
Test set:  MSE=63.242860221905644 R2=0.15125173984613727

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.070e+03, tolerance: 3.112e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.175e+03, tolerance: 3.112e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.217e+03, tolerance: 3.112e+00

In [155]:
from sklearn.model_selection import cross_val_score

In [156]:
elastic = ElasticNet(alpha=0.01, l1_ratio=0.5)
elastic.fit(X_train_poly, y_train)

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.217e+03, tolerance: 3.112e+00

ElasticNet(alpha=0.01)

In [157]:
X_=X.copy()
X_=polyfeats.fit_transform(X_)
X_=ss.fit_transform(X_)

In [158]:
X_.shape

(506, 105)

In [159]:
score=cross_val_score(elastic,X_,y,cv=5)
score

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.542e+03, tolerance: 3.919e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.551e+03, tolerance: 3.307e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.485e+03, tolerance: 2.814e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.927e+02, tolerance: 3.307e+00

c:\Users\0304f\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.215e+03, tolerance: 3.481e+00

array([0.65295742, 0.68589211, 0.60832034, 0.3562781 , 0.09699599])

In [160]:
score.mean()

0.4800887906590779

In [161]:
import joblib

## to save a model
joblib.dump(elastic,'elastic_model.pkl')

['elastic_model.pkl']

In [162]:
newmodel = joblib.load('elastic_model.pkl')
newmodel

ElasticNet(alpha=0.01)

In [163]:
new_input=pd.DataFrame(X.iloc[0]).T
new_input

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.09,1.0,296.0,15.3,396.9,4.98

In [164]:
x=polyfeats.transform(new_input)
x=ss.transform(x)
x

array([[ 0.        , -0.41978194,  0.28482986, -1.2879095 , -0.27259857,
        -0.14421743,  0.41367189, -0.12001342,  0.1402136 , -0.98284286,
        -0.66660821, -1.45900038,  0.44105193, -1.0755623 , -0.1694739 ,
        -0.35533238, -0.41129446, -0.16025923, -0.41672657, -0.41510069,
        -0.40416155, -0.4907021 , -0.39080682, -0.40292667, -0.41418582,
        -0.37018273, -0.3751219 , -0.19103019,  0.00329155, -0.10160361,
         0.49123308,  0.26241795,  0.97193552, -0.01190279, -0.29665166,
         0.26688376,  0.2188637 ,  0.29946093,  0.09394556, -0.96925324,
        -0.24589724, -1.09780951, -1.29100834, -1.00871004, -1.59941763,
        -0.79506056, -0.9842466 , -1.27959722, -1.10739687, -0.9604953 ,
        -0.27259857, -0.26451161, -0.27006389, -0.26179222, -0.2510544 ,
        -0.20214459, -0.24984173, -0.27060576, -0.26973089, -0.23296246,
        -0.22753001,  0.10661139, -0.24565874,  0.37301906, -0.87022334,
        -0.58051268, -0.78470436,  0.32896513, -0.90655188,  0.35734314,
         0.01409149,  0.19530094, -0.99030779, -0.58287799, -0.98202343,
         0.55874781, -1.13583163, -0.36047624,  0.52454241, -0.8233161 ,
        -0.53032667, -0.4943253 ,  0.18254483, -0.83083534, -0.09942706,
        -1.24406808, -0.23954141, -0.17128681,  0.24115948, -0.88778072,
        -0.68135523, -0.76971415, -0.94271473, -0.89835349, -0.74439041,
        -0.68202398, -0.85112346, -0.33057661, -0.85559373, -1.45842853,
        -0.25877794, -1.11967794,  0.52632759, -0.88025024, -0.78952949]])

In [165]:
x.shape

(1, 105)

In [166]:
newmodel.predict(x)[0]

28.58819897491448